### ISSUE TITLE
 Wvision\Bundle\DataDefinitionsBundle\Model\ExportDefinition::getById(): Argument #1 ($name) must be of type string, int given, called in vendor/coreshop/resource-bundle/Pimcore/PimcoreDaoRepository.php on line 96

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/DataDefinitions#409]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

**Comment by bramstroker** [comment]
Same problem for our projects using data definitions with version 5.0.0 of the bundle.

**Comment by a-strusevich** [comment]
Hello, have same problem for our projects using data definitions with version 5.0. Has anyone solved this themselves?

```
Status: 500 | Internal Server Error
URL: /admin/data_definitions/import_definitions/list?_dc=1712736668981
Method: GET
Message: Instride\Bundle\DataDefinitionsBundle\Model\ImportDefinition\Dao::getByName(): Argument #1 ($id) must be of type ?string, int given, called in /var/www/html/vendor/instride/data-definitions/src/DataDefinitionsBundle/Model/ImportDefinition.php on line 102
Trace: 
in /var/www/html/vendor/instride/data-definitions/src/DataDefinitionsBundle/Model/ImportDefinition/Dao.php:74
#0 /var/www/html/vendor/instride/data-definitions/src/DataDefinitionsBundle/Model/ImportDefinition.php(102): Instride\Bundle\DataDefinitionsBundle\Model\ImportDefinition\Dao->getByName(135)
#1 /var/www/html/vendor/instride/data-definitions/src/DataDefinitionsBundle/Model/ImportDefinition/Listing/Dao.php(31): Instride\Bundle\DataDefinitionsBundle\Model\ImportDefinition::getByName(135)
#2 [internal function]: Instride\Bundle\DataDefinitionsBundle\Model\ImportDefinition\Listing\Dao->loadList()
#3 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(220): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/instride/data-definitions/src/DataDefinitionsBundle/Model/ImportDefinition/Listing.php(51): Pimcore\Model\AbstractModel->__call('loadList', Array)
#5 /var/www/html/vendor/coreshop/resource-bundle/Pimcore/PimcoreDaoRepository.php(75): Instride\Bundle\DataDefinitionsBundle\Model\ImportDefinition\Listing->getObjects()
#6 /var/www/html/vendor/coreshop/resource-bundle/Controller/ResourceController.php(86): CoreShop\Bundle\ResourceBundle\Pimcore\PimcoreDaoRepository->findAll()
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): CoreShop\Bundle\ResourceBundle\Controller\ResourceController->listAction(Object(Symfony\Component\HttpFoundation\Request))
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#12 /var/www/html/public/index.php(19): require_once('/var/www/html/v...')
#13 {main}
```

**Comment by dkarlovi** [comment]
@bramstroker @a-strusevich @twin-elements feel free to PR here.
